In [ ]:
#Maha Albash - Aljawhara Albawardi
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
dataset = {
    "Name": ["Maha", "Aljawhara", "Noor","Sara"],
    "Age": [20, 20, 22,25],
    "City": ["Italia", "London", "Paris","Saudi Arabia"]
}

dataset

{'Name': ['Maha', 'Aljawhara', 'Noor', 'Sara'],
 'Age': [20, 20, 22, 25],
 'City': ['Italia', 'London', 'Paris', 'Saudi Arabia']}

In [ ]:
df = pd.DataFrame(dataset)
print("Pandas Data Frame:")
df

Pandas Data Frame:


Name  Age          City
0       Maha   20        Italia
1  Aljawhara   20        London
2       Noor   22         Paris
3       Sara   25  Saudi Arabia

In [ ]:
dataages = pd.DataFrame(df["Age"])
dataages

Age
0   20
1   20
2   22
3   25

In [ ]:
age_above_22 = pd.DataFrame(df[df["Age"] > 22])
age_above_22

Name  Age          City
3  Sara   25  Saudi Arabia

In [ ]:
df["career"] = ["programmer", "programmer", "doctor","doctor"]
print("DataFrame with new column:\n")
df

DataFrame with new column:



Name  Age          City      career
0       Maha   20        Italia  programmer
1  Aljawhara   20        London  programmer
2       Noor   22         Paris      doctor
3       Sara   25  Saudi Arabia      doctor

In [ ]:
df["Age"] = df["Age"] + 1
print("DataFrame with modified Age:\n")
df

DataFrame with modified Age:



Name  Age          City      career
0       Maha   21        Italia  programmer
1  Aljawhara   21        London  programmer
2       Noor   23         Paris      doctor
3       Sara   26  Saudi Arabia      doctor

In [ ]:
data_with_nan = {
    "Name": ["Hessa", "Reema", None],
    "Age": [15, None, 10],
    "City": ["Dubai", "Qatar", None]
}
df_nan = pd.DataFrame(data_with_nan)
print("DataFrame with missing values:\n")
df_nan

DataFrame with missing values:



Name   Age   City
0  Hessa  15.0  Dubai
1  Reema   NaN  Qatar
2   None  10.0   None

In [ ]:
df_filled = df_nan.fillna("Huda")
print("DataFrame with filled missing values:\n")
df_filled

DataFrame with filled missing values:



Name   Age   City
0  Hessa  15.0  Dubai
1  Reema  Huda  Qatar
2   Huda  10.0   Huda

In [ ]:
import pandas as pd
data = {
    "Feature1": [6, 7, 8, 9, 50],
    "Feature2": [3, 44, 55, 7, 23]
}
df_stats = pd.DataFrame(data)
df_stats

Feature1  Feature2
0         6         3
1         7        44
2         8        55
3         9         7
4        50        23

In [ ]:
std_dev = df_stats.std()
print("Standard Deviation of each column:\n")
std_dev

Standard Deviation of each column:



Feature1    19.039433
Feature2    22.711231
dtype: float64

In [12]:
!pip install numpy

In [13]:
import numpy as np

In [ ]:
array_1D = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1D)

1D Array: [1 2 3 4 5]


In [ ]:
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix):\n", array_2D)

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
array_3D = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                     [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print("3D Array:\n", array_3D)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [28]:
print("1D Array:", array_1D)
sum_array = np.sum(array_1D)
print("Sum of 1D Array:", sum_array)
mean_array = np.mean(array_1D)
print("Mean of 1D Array:", mean_array)
squared_array = np.square(array_1D)
print("Squared 1D Array:", squared_array)

1D Array: [1 2 3 4 5]
Sum of 1D Array: 15
Mean of 1D Array: 3.0
Squared 1D Array: [ 1  4  9 16 25]


In [24]:
(5,)

(5,)

In [26]:
reshaped_array = array_1D.reshape((5, 1))
print("Reshaped Array (1D to 2D):\n", reshaped_array)

Reshaped Array (1D to 2D):
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [14]:
transposed_matrix = np.transpose(array_2D)
print("2D Array (Matrix):\n", array_2D)
print("Transposed Matrix:\n", transposed_matrix)

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [25]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print("matrix_a:\n", matrix_a)
print("matrix_b:\n", matrix_b)
matrix_product = np.dot(matrix_a, matrix_b)
print("Matrix Product:\n", matrix_product)

matrix_a:
 [[1 2]
 [3 4]]
matrix_b:
 [[5 6]
 [7 8]]
Matrix Product:
 [[19 22]
 [43 50]]


In [18]:
std_dev = np.std(array_1D)
print("Standard Deviation of 1D Array:", std_dev)
random_numbers = np.random.randn(3, 3)
print("Random Numbers:\n", random_numbers)


Standard Deviation of 1D Array: 1.4142135623730951
Random Numbers:
 [[ 0.18443956  2.01339098 -1.04015598]
 [ 1.67428889  1.01483042 -1.45163103]
 [ 1.10748154  0.23423561  1.48748159]]


In [19]:
dataset = np.random.rand(10, 3)
print("Dataset:\n", dataset)


Dataset:
 [[0.20249533 0.58328128 0.42336636]
 [0.27722764 0.41206356 0.95922049]
 [0.45466626 0.51437599 0.73323427]
 [0.56758471 0.38465595 0.62295811]
 [0.46539617 0.04956059 0.3790634 ]
 [0.47107955 0.6319887  0.62210616]
 [0.23968812 0.78056165 0.49022049]
 [0.69725805 0.14208614 0.53151225]
 [0.73716527 0.78803356 0.14137247]
 [0.94222672 0.07900168 0.98771114]]


In [20]:
dataset [0]

array([0.20249533, 0.58328128, 0.42336636])

In [21]:
dataset [:,0]

array([0.20249533, 0.27722764, 0.45466626, 0.56758471, 0.46539617,
       0.47107955, 0.23968812, 0.69725805, 0.73716527, 0.94222672])

In [23]:
feature_column = dataset[:,1]
print("Selected Feature Column:\n", feature_column)

Selected Feature Column:
 [0.58328128 0.41206356 0.51437599 0.38465595 0.04956059 0.6319887
 0.78056165 0.14208614 0.78803356 0.07900168]


In [22]:
train_size = int(0.8 * dataset.shape[0])
train_set, test_set = dataset[:train_size], dataset[train_size:]
print("Training Set:\n", train_set)
print("Test Set:\n", test_set)

Training Set:
 [[0.20249533 0.58328128 0.42336636]
 [0.27722764 0.41206356 0.95922049]
 [0.45466626 0.51437599 0.73323427]
 [0.56758471 0.38465595 0.62295811]
 [0.46539617 0.04956059 0.3790634 ]
 [0.47107955 0.6319887  0.62210616]
 [0.23968812 0.78056165 0.49022049]
 [0.69725805 0.14208614 0.53151225]]
Test Set:
 [[0.73716527 0.78803356 0.14137247]
 [0.94222672 0.07900168 0.98771114]]
